config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :goals do
    resources :amounts
  end

  root 'welcome#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
	validates :points, numericality: { only_integer: true }

	belongs_to :goal
end

app/models/goal.rb
class Goal < ActiveRecord::Base
	has_many :amounts, dependent: :destroy

	accepts_nested_attributes_for :amounts
end

app/controllers/amounts_controller.rb
class AmountsController < ApplicationController
	protect_from_forgery
	
	def create
		@goal = Goal.find(params[:goal_id])
		@amount = @goal.amounts.create(amount_params)
		
		if @amount.save
			redirect_to goal_path(@goal)
		else
			render @goal
		end
	end

	def destroy
		@goal = Goal.find(params[:goal_id])
		@amount = @goal.amounts.find(params[:id])
		@amount.destroy
		redirect_to goal_path
	end

	def update
		@goal = Goal.find(params[:goal_id])
		@amount = @goal.amounts

		if @amount.update(amount_params)
			redirect_to @goal
		else
			render @goal
		end
	end

	private
		def amount_params
			params.require(:amount).permit(:goal_amount, :points)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	def index
		@goals = Goal.all
		@amount = @goal.amounts.build
	end

	def show
		@goal = Goal.find(params[:id])
		@amount = @goal.amounts.build
	end

	def new
		@goal = Goal.new
	end

	def edit
		@goal = Goal.find(params[:id])
		@amount = @goal.amounts
	end

	def create
		@goal = Goal.new(goal_params)

		if @goal.save
			redirect_to @goal
		else
			render 'new'
		end
	end

	def update
		@goal = Goal.find(params[:id])

		if @goal.update(goal_params)
			redirect_to @goal
		else
			render 'edit'
		end
	end

	def destroy
		@goal = Goal.find(params[:id])
		@goal.destroy

		redirect_to welcome_index_path
	end

	private
		def goal_params
			params.require(:goal).permit(:title, :test)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 def index
		@goals = Goal.all
		@goal = Goal.new
	end

	private
		def goal_params
			params.require(:goal).permit(:title)
		end
end

app/helpers/amounts_helper.rb
module AmountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goals/_form.html.erb
<% if @amount.errors.any? %>
	<div id="error explanation">
		<h2><%= pluralize(@amount.errors.count, "error") %>
			prohibited this goal from being saved:</h2>
		<ul>
			<% @amount.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for([@goal, @goal.amounts.build]) do |f| %>
	<h2>Is this correct?</h2>
	<%= f.text_field :goal_amount %>
	<%= @goal.test %>
	of
	<%= @goal.title %><br>
	<h2>How many points is this goal worth?</h2>
	<%= f.text_field :points %>

	<h2>Would you like to add other incements for more points?</h2>
	<%= f.submit %>
<% end %>

app/views/goals/edit.html.erb
<h1>Let's fix up this goal.</h1>

<% @goal.amounts.each do |amount| %>
	<p>
		<strong><%= amount.points %> Points: </strong>
		<%= amount.goal_amount %> of <%= @goal.title %>
		<%= link_to 'Edit', edit_goal_path(@goal) %>
	</p>
<% end %>

<%= link_to 'Back', welcome_index_path %>

app/views/goals/index.html.erb
<h1>Welcome Back, USER!</h1>
<%= link_to 'Would you like to add a new goal?', new_goal_path %>
<% count = 0 %>

<% @goals.each do |goal| %>
	<table>
		<tr>
			<th>Today's Goals:</th>
		</tr>
	<% @goal = Goal.find goal.id %>
	<% @goal.amounts.each do |amount| %>
		<tr>
			<td><%= amount.goal_amount %> <%= goal.title %></td>
			<td><%= link_to 'Show', goal_path(goal) %></td>
			<td><%= link_to 'Edit', edit_goal_path(goal) %></td>
			<td><%= link_to 'Delete', goal_path(goal), method: :delete,
				data: {	confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>
	</table>
<% end %>

<h2>Add a new goal</h2>
<% form_for @goal do |f| %>
	<%= f.text_field :title %>
	<%= f.submit %>
<% end %>

app/views/goals/new.html.erb
<h1>Let's get motivated</h1>

<%= render 'form' %>

<%= link_to "Back", welcome_index_path %>

app/views/goals/show.html.erb
<h1>Let's check out this goal.</h1>

<% @goal.amounts.each do |amount| %>
	<p>
		<strong><%= amount.points %> Points: </strong>
		<%= amount.goal_amount %> of <%= @goal.title %>
		<%= link_to 'Edit', edit_goal_path(@goal) %>
		<%= link_to 'Destroy Amount', goal_amounts_path(amount.goal, amount), method: :delete, data: { confirm: "Are you sure?" } %>
	</p>
<% end %>

<% if @amount.errors.any? %>
	<div id="error explanation">
		<h2><%= pluralize(@amount.errors.count, "error") %>
			prohibited this goal from being saved:</h2>
		<ul>
			<% @amount.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for([@goal, @goal.amounts.build]) do |f| %>
	<h2>Is this correct?</h2>
	<%= f.text_field :goal_amount %>
	<%= @goal.test %>
	of
	<%= @goal.title %><br>
	<h2>How many points is this goal worth?</h2>
	<%= f.text_field :points %>

	<h2>Would you like to add other incements for more points?</h2>
	<%= f.submit %>
<% end %>

<strong>Add goal amount</strong>
<%= form_for([@goal, @goal.amounts.build]) do |f| %>
	<p>
		<%= f.label :goal_amount %><br>
		<%= f.text_field :goal_amount %>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to 'Edit', edit_goal_path(@goal) %> | 
<%= link_to 'Back', welcome_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sampleapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/_form.html.erb
<%= form_for @goal do |f| %>
	<% if @goal.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@goal.errors.count, "error") %> prohibited
					this goal from being saved:
			</h2>
			<ul>
				<% @goal.errors.full_messages.each do |msg| %>
					<li><% msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<strong>I'm going to start doing </strong><%= f.text_field :test, placeholder: "this is a test" %> of <%= f.text_field :title, placeholder: "exercise, words, cleaning" %>
	</p>
		<%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome Back, USER!</h1>
<%= link_to 'Would you like to add a new goal?', new_goal_path %>
<% count = 0 %>

<h2>Add a new goal</h2>
<%= render 'form' %>

<% @goals.each do |goal| %>
	<table>
		<tr>
			<th>Today's Goals:</th>
		</tr>
	<% @goal = Goal.find goal.id %>
	<% @goal.amounts.each do |amount| %>
		<tr>
			<td><strong><%=amount.points %></strong><%= amount.goal_amount %> <%= goal.title %></td>
			<td><%= link_to 'Show', goal_path(goal) %></td>
			<td><%= link_to 'Edit', edit_goal_path(goal) %></td>
			<td><%= link_to 'Delete', goal_path(goal), method: :delete,
				data: {	confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>
	</table>
<% end %>